from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src     = Glob('*.c')


src += Glob('stm32_radio_driver/*.c')
src += Glob('common/*.c')
CPPPATH += [cwd + '/stm32_radio_driver']
CPPPATH += [cwd + '/common']

group = DefineGroup('SubGHz_Phy', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
