RM := rm -rf
BRIDGE_EXE := studio-mdk-bridge.exe
UV4_EXE := "D:\softwares_for_learning\Keil_v5\UV4\UV4.exe"
UVPROJX_LOC := "F:\qianrushi\rt_thread-lm401_PingPong_V1.0_202209\project.uvprojx"

.PHONY: mdk_all

mdk_all:
	-$(BRIDGE_EXE) --build --uv4-path $(UV4_EXE) $(UVPROJX_LOC)

mdk_clean:
	-@$(RM) *
	@echo 'success'



*.elf: $(wildcard ..)
